### ISSUE TITLE
Objective-C Garbage Collection

### ISSUE THREAD

**Issue by aaronmehar** [Lord-Kamina/Deluge-Magnet-Handler#2]
Hey!

Great plugin.. has been working awesomely for ages.., I updated the mac to sierra and now get this..

<img width="427" alt="screen shot 2016-08-19 at 20 46 27" src="https://cloud.githubusercontent.com/assets/8697411/17822261/0e8b4f5c-664e-11e6-9ce2-d54dd8b4b208.png">

**Comment by Lord-Kamina** [comment]
I have no idea whether I can correct that at all... The plug-in basically
acts like glue between different apps (and languages) made by other
people... I guess the first step would be to try and pinpoint what exactly
is giving that error.

Can you open a terminal and go inside the application bundle, to the
Resources directory and try running lstool directly? If the problem is with
lstool I have no idea whether we'll be able to fix it.

**Comment by JHurk** [comment]
I have the same problem and followed this tread, but because of the lack of reply I am jumping in. Hopefully I am able to help pinpoint the problem.
I am not really familiar with terminal, but maybe the following helps:

When I run the script in Scripteditor I get this reply/outcome:

tell application "Finder"
    get application file id "org.deluge.MagnetURIHandler"
        --> "Macintosh HD:Applications:Magnet Handler.app"
end tell
(_/Applications/Magnet Handler.app_)
tell current application
    do shell script "'/Applications/Magnet Handler.app/Contents/Resources/lstool' read url magnet"
        --> error "objc[42416]: Objective-C garbage collection is no longer supported." number 1006
Resultaat:
error "objc[42416]: Objective-C garbage collection is no longer supported." number 1006

If I need to look into something else, please provide a detailed step-by-step plan.
Thanks for looking into this.

**Comment by aaronmehar** [comment]
I was meant to reply to this before.. this does still actually work. This seems to be a warning for now, or a function (perhaps a clean up) that is not functioning.

@JHurk The terminal is showing the same error message as the pop-up

**Comment by Lord-Kamina** [comment]
So, the error is indeed in lstool. That's kind of a shame because lstool is
the core of one of the coolest apps ever, but is not opensource (and it's
basically abandoned; I sent an email to the developer to ask for the source
but got no reply). The only fix I can devise in the short/medium term is to
attempt to code a few lines to do this myself.

**Comment by JHurk** [comment]
Thanks, for both of your replies.
But for me it is not working. Maybe it is because I installed the script after I installed macOS Sierra.
So Deluge has never been associated with magnet links and therefor it can't make the initial connection between magnet links and Deluge.
My magnet links are still associated to Remote Download Station (Synology) and I can't change this as far as I know.

**Comment by baemien** [comment]
I'm having the same issue :(

**Comment by Lord-Kamina** [comment]
This is a problem with an app I didn't code and was using as a backend. The
app is free but not open-source so even though correcting it would probably
be trivial, I cannot do it. I'm experimenting with trying to get it to run
on Sierra, but if I just can't, I'll just throw together a simpler app that
serves the same purpose for the specific case of magnet URIs.

**Comment by maleorderbride** [comment]
I found a workaround using RCDefaultApp to to start Deluge Magnet Handler for first-time association in Sierra 10.12.0.
1. Download and install RCDefaultApp, then associate Extensions and UTIs 
2. Click on a magnet link, accept the browser warning, and then Deluge Magnet Handler should start.
3. Choose to associated magnet links per usual.

**Comment by Lord-Kamina** [comment]
Internally, this plug-in ran exactly the same app as RCDefaultApp does. Either way, I've written a very brief and basic swift utility in an attempt to forgo the need for lstool/RCDefaultApp entirely. Give https://github.com/Lord-Kamina/Deluge-Magnet-Handler/releases/tag/1.2.0 a try.

**Comment by Almagestum** [comment]
If you are doing a fresh Sierra install. Don't use the install method listed as it creates this corruption.

Download and extract the zip don't don't touch anything inside. Click on a magnet link, when ask what program to choose browse and select Magnet Handler. This should create correct pathways and prevents this corruption dialogue shown above.

Enjoy.

**Comment by Lord-Kamina** [comment]
It is not "corruption", it's just that RCDefaultApps is very old and hasn't
been updated in forever. The latest version I uploaded uses a small Swift
script to associate itself, instead of the command-line version of
RCDefaultApps.
