### ISSUE TITLE
High Sierra? Doesn't work

### ISSUE THREAD

**Issue by iogitio** [Lord-Kamina/Deluge-Magnet-Handler#4]
I've downloaded the app, opened it, I get the dialog box and click "yes" ... but MacOS High Sierra doesn't make the magnet link association to the App... is it the app or me? :)

**Comment by Lord-Kamina** [comment]
I’m still on Sierra myself so honestly cannot say. I’ll soon get a new mac
and then I’ll move to 10.13; most likely at some point I’ll rewrite the
whole app in Swift though.

-- 
Gregorio Litenstein Goldzweig
[image: glit_ind.png]
Médico Cirujano



   - Fono:  +56 9 96343643
   - E-Mail:  g.litenstein@gmail.com


On March 7, 2018 at 03:29:35, iogitio (notifications@github.com) wrote:

I've downloaded the app, opened it, I get the dialog box and click "yes"
... but MacOS High Sierra doesn't make the magnet link association to the
App... is it the app or me? :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Lord-Kamina/Deluge-Magnet-Handler/issues/4>, or mute
the thread

**Comment by iogitio** [comment]
Does this issue seem High Sierra specific? Not sure why it wouldn't work

**Comment by Lord-Kamina** [comment]
You're the first to report this but OTOH I don't really know how many people use this. I can't think of a particular reason for why it might not work either but it's just I've had some ugly surprises with regards to High Sierra. For example, a prefpane I wrote 100% in Swift4 refuses to run on 10.13 because reasons.

This app in particular is mostly AppleScript but it uses a small Swift utility to actually register the magnet scheme. It's hard to know what is even failing. I assume you did extract it to Applications AND you have gatekeeper off. Maybe after the initial run try checking your browser settings to see what it's trying to do with magnets?

**Comment by iogitio** [comment]
Figured it out... you must enable the script/app inside Security preference Pane. Also, if you have Transmission installed (want to have two clients), you need to delete it, run the app to register the magnet URI, then reinstall Transmission. 

thanks for the hint!
